Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 19:46:57
Django version 4.2, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Not Found: /backend/
[19/Apr/2023 19:48:21] "GET /backend/ HTTP/1.1" 404 2563
[19/Apr/2023 19:48:48] "GET /events HTTP/1.1" 301 0
[19/Apr/2023 19:48:48] "GET /events/ HTTP/1.1" 200 17564
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 19:52:31
Django version 4.2, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 19:57:53
Django version 4.2, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

CommandError: "127.0.0.8000" is not a valid port number or address:port pair.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 20:01:19
Django version 4.2, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 20:02:29
Django version 4.2, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Error: That port is already in use.
[19/Apr/2023 20:12:24] "GET /events/ HTTP/1.1" 200 17564
[19/Apr/2023 20:12:47] "GET /cities/ HTTP/1.1" 200 73
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 20:43:41
Django version 4.2, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /events/
[19/Apr/2023 20:49:33] "GET /events/ HTTP/1.1" 400 64325
Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[19/Apr/2023 20:49:33] "GET /favicon.ico HTTP/1.1" 400 64091
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 20:58:38
Django version 4.2, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Error: That port is already in use.
Unknown command: '0.0.0.0.8000'
Type 'manage.py help' for usage.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 21:43:37
Django version 4.2, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /cities/
[19/Apr/2023 21:43:55] "GET /cities/ HTTP/1.1" 400 64367
Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[19/Apr/2023 21:43:56] "GET /favicon.ico HTTP/1.1" 400 64133
/home/namenroodle/git/CS499/react-django/backend/backend/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 21:45:04
Django version 4.2, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /cities/
[19/Apr/2023 21:45:12] "GET /cities/ HTTP/1.1" 400 64415
Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[19/Apr/2023 21:45:13] "GET /favicon.ico HTTP/1.1" 400 64181
Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /cities/
[19/Apr/2023 21:47:14] "GET /cities/ HTTP/1.1" 400 64415
Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/namenroodle/miniconda3/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.209.255.177:8000'. You may need to add '35.209.255.177' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[19/Apr/2023 21:47:15] "GET /favicon.ico HTTP/1.1" 400 64181
